# Generated by Django 4.2.5 on 2023-10-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('idurl', models.CharField(blank=True, max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Links',
            },
        ),
    ]
