# Generated by Django 4.2.5 on 2023-10-04 08:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('links', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='link',
            old_name='fecha',
            new_name='date',
        ),
    ]
